name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: python -m pip install contest
    - working-directory: samples/01_hello_world
      run: make test
    - working-directory: samples/02_matrix
      run: make test
    - working-directory: samples/03_kwargs
      run: make test
